### ISSUE TITLE
tidytacos::add_alpha() changed

### ISSUE THREAD

**Issue by slambrechts** [inbo/mbag-bodem#29]
Oplossing is denk ik:

`tidytacos::add_alpha()`

aanpassen naar:

`tidytacos::add_alphas(methods = "all")`

en `observed `in al de Rmd's aanpassen naar `obs`

Vraag ook gesteld op https://github.com/LebeerLab/tidytacos/issues/56

To do: aanpassen in al de Rmd's

**Comment by nick-dil** [comment]
This is a great example of why we might want to centralize the analysis code and use it as/to `source()`
