### ISSUE TITLE
Update `Olig01` en `Coll01` data combined dataframe

### ISSUE THREAD

**Issue by hansvancalster** [inbo/mbag-bodem#36]
@hansvancalster ik besef dat voor `Olig01` en `Coll01` hier nog de input data gebruikt wordt waar OTUs van eenzelfde soort zijn samengevoegd voor de OTUs die we op naam hebben kunnen brengen op soortniveau. Bij nader inzien lijkt dat niet ideaal, want als er bijvoorbeeld een categorie is waar meer gekende soorten zijn gedetecteerd (e.g. `natuurgrasland`) dan in andere LU categoriën, dan worden deze samengevoegd, terwijl de OTUs die we niet tot op soortniveau op naam hebben kunnen brengen apart worden geteld, waardoor de overall species richness count voor deze LU categorie naar beneden gaat tov de categoriën waar (eventueel) minder gekende soorten gedetecteerd zijn.

Ik weet niet of je de html al hebt gereknit, maar we zullen dus de data in 

`G:/Gedeelde drives/PRJ_MBAG/4c_bodembiodiversiteit/data/statistiek/dataframe_overkoepelend/mbag_combined_dataframe_v2.csv` 

updaten voor `Olig01` en `Coll01`

_Originally posted by @slambrechts in https://github.com/inbo/mbag-bodem/issues/31#issuecomment-2511733783_

**Comment by hansvancalster** [comment]
@slambrechts ik heb je comment naar een issue omgevormd

**Comment by slambrechts** [comment]
Silke had toch reeds de juiste input data gebruikt voor `Coll01` en `Olig01`, dus dit is toch geen issue
