### ISSUE TITLE
Correcte manier om nieuw script toe te voegen aan deze github

### ISSUE THREAD

**Issue by slambrechts** [inbo/mbag-bodem#5]
Ik heb samen met Silke [dit script](https://gist.github.com/PietrH/8256a415f48039378f7aeeee604a3664) aangepast, en ik wou de aangepaste versie op de correcte manier toevoegen aan deze github. 

1. Ik heb een fork gemaakt van die gist
2. Dan een nieuwe branch gemaakt in onze mbag-bodem github met als naam `check_occurences_GBIF`
3. Dan in mijn Rstudio terminal naar die nieuwe branch genavigeerd 
4. git clone https://gist.github.com/slambrechts/e90001e4c7cfd504e6caf660b568a3ac
5. cloned R script geopend (met File - Open) en bewerkt in Rstudio desktop
6. Commit and pushed changes

Volgens mij zijn er verschillende dingen fout gelopen:

1. In ons R-project `mbag-bodem` op mijn Rstudio heb ik de voorbije weken ook andere scripts geopend en gelopen waar ik snel dingen in deed zonder te koppelen met een github. Ik denk dat hij bij bovenstaande commit and push deze scripten die nog open stonden in Rstudio ook wou toevoegen aan deze github? Als ik het goed begrijp is dus de eerste fout: geen andere scripten laten open staan, want anders gaan die mee in de push / commit?
2. Ik wou de changes dus laten toevoegen aan de nieuwe branch die ik heb gemaakt, maar ik weet dus niet of dit is gelukt, want in de pull request zag ik dat hij probeerde te mergen met de main ipv met deze nieuwe branch
3. Het script dat ik wou toevoegen was nergens te bespeuren in de pull request

**Comment by hansvancalster** [comment]
In [deze workflow](https://inbo.github.io/git-course/workflow_review.html) en [deze](https://inbo.github.io/git-course/workflow_rstudio.html) kan je wat best practices vinden. Om te helpen met de problemen hierboven zitten we inderdaad best eens samen.
